blank_issues_enabled: true
contact_links:
  - name: ğŸ‘¥ BioCypher GitHub Discussions
    url: https://github.com/biocypher/biocypher/discussions
    about: Please ask questions and participate in our long-term discussions here.

  - name: ğŸŒ "BioCypher Zulip Channel"
    url: https://biocypher.zulipchat.com/
    about: Please ask for support here.
