Title: BioCypher python module configuration file

# Neo4j connection using credentials
neo4j_uri: neo4j://localhost:7687
neo4j_db: neo4j # DB name
neo4j_user: neo4j # user name
neo4j_pw: neo4j # password
insert_batch_size: 30000

# Neo4j admin import batch writer settings
csv_delimiter: 'Â¦'
csv_array_delimiter: '|'
csv_quote_char: '"'
csv_batch_size: 1000000

# Path to the log directory
logdir: biocypher-log

# Logging granularity
# Set debug to true if more granular logging is desired
debug: true

# Path to the output directory
outdir: biocypher-out
